// Skills served by MCP (skill-seeker) rather than installed on disk.
// The disk scanner cannot see these — `~/.claude/skills/` contains zero
// gws-*/recipe-*/persona-* directories — so they are listed here (ADR-0005).
//
// To refresh: compare against the available-skills list in a live session and
// add anything missing. Names must match exactly; descriptions feed search.

const MCP_SKILLS = [
  // ─── Google Workspace: core surfaces ───
  { name: 'gws-gmail', description: 'Gmail 郵件讀取、搜尋與管理' },
  { name: 'gws-gmail-read', description: '讀取指定 Gmail 郵件內容' },
  { name: 'gws-gmail-send', description: '寄送 Gmail 郵件' },
  { name: 'gws-gmail-reply', description: '回覆 Gmail 郵件' },
  { name: 'gws-gmail-reply-all', description: '回覆全部收件者' },
  { name: 'gws-gmail-forward', description: '轉寄 Gmail 郵件' },
  { name: 'gws-gmail-triage', description: 'Gmail 收件匣分類整理' },
  { name: 'gws-gmail-watch', description: '監控 Gmail 新郵件事件' },
  { name: 'gws-calendar', description: 'Google 日曆行程查詢與管理' },
  { name: 'gws-calendar-agenda', description: '取得日曆議程總覽' },
  { name: 'gws-calendar-insert', description: '新增日曆行程' },
  { name: 'gws-drive', description: 'Google Drive 檔案瀏覽與搜尋' },
  { name: 'gws-drive-upload', description: '上傳檔案到 Google Drive' },
  { name: 'gws-docs', description: 'Google Docs 文件讀取' },
  { name: 'gws-docs-write', description: '建立或編輯 Google Docs 文件' },
  { name: 'gws-sheets', description: 'Google Sheets 試算表操作' },
  { name: 'gws-sheets-read', description: '讀取試算表資料' },
  { name: 'gws-sheets-append', description: '附加資料列到試算表' },
  { name: 'gws-slides', description: 'Google Slides 簡報操作' },
  { name: 'gws-forms', description: 'Google Forms 表單與回應' },
  { name: 'gws-tasks', description: 'Google Tasks 待辦事項' },
  { name: 'gws-keep', description: 'Google Keep 記事' },
  { name: 'gws-chat', description: 'Google Chat 訊息' },
  { name: 'gws-chat-send', description: '發送 Google Chat 訊息' },
  { name: 'gws-meet', description: 'Google Meet 會議管理' },
  { name: 'gws-classroom', description: 'Google Classroom 課程管理' },
  { name: 'gws-people', description: 'Google 聯絡人管理' },
  { name: 'gws-script', description: 'Google Apps Script 操作' },
  { name: 'gws-script-push', description: '推送 Apps Script 程式碼' },
  { name: 'gws-admin-reports', description: 'Workspace 管理報表' },
  { name: 'gws-events', description: 'Workspace 事件訂閱管理' },
  { name: 'gws-events-subscribe', description: '訂閱 Workspace 事件' },
  { name: 'gws-events-renew', description: '更新事件訂閱' },
  { name: 'gws-shared', description: 'Workspace 共用資源存取' },
  { name: 'gws-workflow', description: 'Workspace 跨服務流程' },
  { name: 'gws-workflow-email-to-task', description: '郵件轉待辦事項' },
  { name: 'gws-workflow-file-announce', description: '檔案更新通知流程' },
  { name: 'gws-workflow-meeting-prep', description: '會議準備流程' },
  { name: 'gws-workflow-standup-report', description: '每日站會report流程' },
  { name: 'gws-workflow-weekly-digest', description: '每週摘要流程' },
  { name: 'gws-modelarmor', description: 'Model Armor 內容安全防護' },
  { name: 'gws-modelarmor-create-template', description: '建立 Model Armor 範本' },
  { name: 'gws-modelarmor-sanitize-prompt', description: '淨化輸入提示' },
  { name: 'gws-modelarmor-sanitize-response', description: '淨化模型回應' },

  // ─── Persona workflows ───
  { name: 'persona-content-creator', description: '內容創作者角色工作流' },
  { name: 'persona-customer-support', description: '客服角色工作流' },
  { name: 'persona-event-coordinator', description: '活動統籌角色工作流' },
  { name: 'persona-exec-assistant', description: '行政助理角色工作流' },
  { name: 'persona-hr-coordinator', description: '人資角色工作流' },
  { name: 'persona-it-admin', description: 'IT 管理角色工作流' },
  { name: 'persona-project-manager', description: '專案經理角色工作流' },
  { name: 'persona-researcher', description: '研究員角色工作流' },
  { name: 'persona-sales-ops', description: '業務營運角色工作流' },
  { name: 'persona-team-lead', description: '團隊主管角色工作流' },

  // ─── Recipes: single concrete tasks across services ───
  { name: 'recipe-backup-sheet-as-csv', description: '備份試算表為 CSV' },
  { name: 'recipe-batch-invite-to-event', description: '批次邀請參加活動' },
  { name: 'recipe-block-focus-time', description: '在日曆封鎖專注時段' },
  { name: 'recipe-bulk-download-folder', description: '批次下載 Drive 資料夾' },
  { name: 'recipe-collect-form-responses', description: '收集表單回應' },
  { name: 'recipe-compare-sheet-tabs', description: '比對試算表分頁差異' },
  { name: 'recipe-copy-sheet-for-new-month', description: '複製試算表供新月份使用' },
  { name: 'recipe-create-classroom-course', description: '建立 Classroom 課程' },
  { name: 'recipe-create-doc-from-template', description: '依範本建立文件' },
  { name: 'recipe-create-events-from-sheet', description: '從試算表批次建立行程' },
  { name: 'recipe-create-expense-tracker', description: '建立支出追蹤表' },
  { name: 'recipe-create-feedback-form', description: '建立意見回饋表單' },
  { name: 'recipe-create-gmail-filter', description: '建立 Gmail 篩選器' },
  { name: 'recipe-create-meet-space', description: '建立 Meet 會議空間' },
  { name: 'recipe-create-presentation', description: '建立簡報' },
  { name: 'recipe-create-shared-drive', description: '建立共用雲端硬碟' },
  { name: 'recipe-create-task-list', description: '建立待辦清單' },
  { name: 'recipe-create-vacation-responder', description: '設定休假自動回覆' },
  { name: 'recipe-draft-email-from-doc', description: '從文件草擬郵件' },
  { name: 'recipe-email-drive-link', description: '寄送 Drive 檔案連結' },
  { name: 'recipe-find-free-time', description: '尋找共同空檔時段' },
  { name: 'recipe-find-large-files', description: '找出佔空間的大型檔案' },
  { name: 'recipe-forward-labeled-emails', description: '轉寄特定標籤郵件' },
  { name: 'recipe-generate-report-from-sheet', description: '從試算表產生報告' },
  { name: 'recipe-label-and-archive-emails', description: '標記並封存郵件' },
  { name: 'recipe-log-deal-update', description: '記錄交易進度更新' },
  { name: 'recipe-organize-drive-folder', description: '整理 Drive 資料夾' },
  { name: 'recipe-plan-weekly-schedule', description: '規劃每週行程' },
  { name: 'recipe-post-mortem-setup', description: '建立事後檢討文件' },
  { name: 'recipe-reschedule-meeting', description: '重新安排會議時間' },
  { name: 'recipe-review-meet-participants', description: '檢視會議參與者' },
  { name: 'recipe-review-overdue-tasks', description: '檢視逾期待辦' },
  { name: 'recipe-save-email-attachments', description: '儲存郵件附件' },
  { name: 'recipe-save-email-to-doc', description: '將郵件存成文件' },
  { name: 'recipe-schedule-recurring-event', description: '排定重複性行程' },
  { name: 'recipe-send-team-announcement', description: '發送團隊公告' },
  { name: 'recipe-share-doc-and-notify', description: '分享文件並通知' },
  { name: 'recipe-share-event-materials', description: '分享活動資料' },
  { name: 'recipe-share-folder-with-team', description: '與團隊分享資料夾' },
  { name: 'recipe-sync-contacts-to-sheet', description: '同步聯絡人到試算表' },
  { name: 'recipe-watch-drive-changes', description: '監控 Drive 檔案異動' },

  // ─── Built-in / harness skills (not on disk either) ───
  { name: 'dataviz', description: '圖表與資料視覺化設計系統，含配色與可及性驗證' },
  { name: 'update-config', description: '設定 Claude Code settings.json、hooks、權限與環境變數' },
  { name: 'keybindings-help', description: '自訂鍵盤快捷鍵與 keybindings.json' },
  { name: 'simplify', description: '審視變更中的程式碼，套用重用與簡化修正' },
  { name: 'fewer-permission-prompts', description: '掃描 transcript 產生允許清單，減少權限詢問' },
  { name: 'loop', description: '依間隔重複執行提示或指令，或自行決定節奏' },
  { name: 'claude-api', description: 'Claude API 與 SDK 參考：模型 ID、定價、串流、工具使用、快取' },
  { name: 'run', description: '啟動並操作專案應用程式以驗證變更' },
  { name: 'review', description: '程式碼審查' },
  { name: 'security-review', description: '安全性審查' },
  { name: 'init', description: '初始化專案設定' },
];

module.exports = { MCP_SKILLS };
